#!/bin/bash

certfile="crawlera-ca.crt"
certname="Crawlera CA"

### For cert8 (legacy - DBM)

for certDB in $(find ~/.pki/nssdb -name "cert8.db")
do
    certdir=$(dirname ${certDB});
    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d dbm:${certdir}
done

### For cert9 (SQL)

for certDB in $(find ~/.pki/nssdb -name "cert9.db")
do
    certdir=$(dirname ${certDB});
    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d sql:${certdir}
done

